### ISSUE TITLE
Oracle Java 8 version gets errors on Ubuntu 18.04.

### ISSUE THREAD

**Issue by gbonazzoli** [loftuxab/alfresco-ubuntu-install#105]
Using today alfinstall.sh script I got the following errors:

```
Install Java JDK.
This will install Oracle Java 8 version of Java. If you prefer OpenJDK
you need to download and install that manually.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Install Oracle Java 8? [y/n] y
Installing Oracle Java 8. Fetching packages...
E: Package 'python-software-properties' has no installation candidate
sudo: add-apt-repository: command not found
W: GPG error: http://nginx.org/packages/mainline/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABF5BD827BD9BF62
E: The repository 'http://nginx.org/packages/mainline/ubuntu bionic InRelease' is not signed.
E: Package 'oracle-java8-installer' has no installation candidate
sudo: update-java-alternatives: command not found

Finished installing Oracle Java 8
```
the script did not recognize the error and continued on.

**Comment by loftux** [comment]
That was quick to test! 
Didn't have the proper test environment for 18.04. You can probably just carry on installing the rest, and then manually install Oracle Java in a way that works. If you find out how, you can update the issue, and I'll try to update the script.

**Comment by digitalarchitects** [comment]
With the current issues on Oracle Java , perhaps it is best to stick to the default openJDK that ships with Ubuntu 18. There is a number of users that are editing the dpkg config file to work around the 404, but I found the easy way was a manual install and using the alternative commands system to 
map /usr/bin/java to the install directory of choice.

**Comment by loftux** [comment]
The script is now changed to use OpenJDK, so closing this issue.
