### ISSUE TITLE
Office Services gets errors on Ubuntu 16.04

### ISSUE THREAD

**Issue by gbonazzoli** [loftuxab/alfresco-ubuntu-install#106]
Using today **alfinstall.sh** script I got the following errors "08060001 An error was encountered during deployment of the AMP into the WAR: 08060000 The module (Alfresco Office Services Module) must be installed on a war version equal to or greater than 6.0. ".

Detailed output:

`Install Alfresco Office Services integration? [y/n] y
Installing Alfresco Offices Services bundle...
Downloading Alfresco Office Services amp file
######################################################################## 100.0%
Downloading _vti_bin.war into tomcat/webapps
######################################################################## 100.0%
Downloading ROOT.war into tomcat/webapps
######################################################################## 100.0%
/usr/bin/java
Applying alfresco/alfresco-aos-module-1.2.0.amp
08060001 An error was encountered during deployment of the AMP into the WAR: 08060000 The module (Alfresco Office Services Module) must be installed on a war version equal to or greater than 6.0. This war is version: 5.2.0.
Applying alfresco/alfresco-googledocs-repo-3.0.4.3.amp
Applying alfresco/alfresco-share-services-LX101.amp
Applying share/alfresco-googledocs-share-3.0.4.3.amp
Module 'alfresco-share-services' installed in 'alfresco.war'
   -    Title:        Alfresco Share Services AMP
   -    Version:      5.2.0
   -    Install Date: Thu Sep 06 10:06:10 UTC 2018
   -    Description:   Module to be applied to alfresco.war, containing APIs for Alfresco Share
Module 'org.alfresco.integrations.google.docs' installed in 'alfresco.war'
   -    Title:        Alfresco / Google Docs Integration
   -    Version:      3.0.4.2
   -    Install Date: Thu Sep 06 10:06:09 UTC 2018
   -    Description:   The Repository side artifacts of the Alfresco / Google Docs Integration.
Module 'org.alfresco.integrations.share.google.docs' installed in 'share.war'
   -    Title:        Alfresco / Google Docs Share Module
   -    Version:      3.0.4.2
   -    Install Date: Thu Sep 06 10:06:11 UTC 2018
   -    Description:   The Share side artifacts of the Alfresco / Google Docs Integration.
`

**Comment by outsider01** [comment]
same here, and the problem is on all amp files. It is not caused by this installer, it is a more generic problem of alfresco 6 i think. I found this script because i ran into a lot of errors with the official 6.x files.
