### ISSUE TITLE
How to fix URL to War files

### ISSUE THREAD

**Issue by alissonjcguedes** [loftuxab/alfresco-ubuntu-install#119]
Hi Guys, 
I could not go ahead:

In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/content-services-community/6.0.7-ga/content-services-community-6.0.7-ga.war
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/share/6.0.c/share-6.0.c.war
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/alfresco-share-services/6.0.c/alfresco-share-services-6.0.c.amp
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/integrations/alfresco-googledocs-repo/3.0.4.3/alfresco-googledocs-repo-3.0.4.3.amp
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/integrations/alfresco-googledocs-share/3.0.4.3/alfresco-googledocs-share-3.0.4.3.amp
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/alfresco-search-services/1.2.0/alfresco-search-services-1.2.0.zip
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/aos-module/alfresco-vti-bin/1.2.0/alfresco-vti-bin-1.2.0.war
In alfinstall.sh, please fix this URL: https://downloads.loftux.net/public/content/org/alfresco/alfresco-server-root/6.0/alfresco-server-root-6.0.war

"Please fix the above errors and rerun"....but i dont know how...
 
Tks in advanced.

**Comment by madcry** [comment]
same here. Urls is broken

**Comment by loftux** [comment]
Hi,

Sorry about his, our dns entry for downloads.loftux.net had gone missing, should be fixed now.
