### ISSUE TITLE
Upload new version action failing when ActiveMQ is not available

### ISSUE THREAD

**Issue by douglascrp** [loftuxab/alfresco-ubuntu-install#120]
The current 6.1 version requires ActiveMQ in order to have Alfresco working propertly, just like described at http://docs.alfresco.com/community/concepts/install-zip-overview.html

The problem I faced when I was using Alfresco without it, as installed by the script, was that the Upload new version action stopped working. The repository was working ok, as the content got updated and a new version is created, but share keeps waiting the api/upload response, which never happened, and then it was failing with a timeout.

The workaround I found was to disable the messaging subsystem, just like this https://community.alfresco.com/thread/240991-endeless-starting-of-messaging-subsystem#comment-842582

So I guess we have some options to improve the script:

1. Inform the user that ActiveMQ is required and should be installed manually;
2. Include the ActiveMQ in the install process automatically;
3. Disable the messaging subsystem including the property messaging.subsystem.autoStart=false into alfresco-global.properties

What do you think?

**Comment by loftux** [comment]
I guess it needs to be installed.
Found this http://docs.alfresco.com/6.0/tasks/activemq-install.html that needs to be added to alfresco-global.properties, but nothing on installing. I guess install doc is not needed when part of docker image. Maybe I can have a look there.

**Comment by douglascrp** [comment]
@loftux You were faster than me

**Comment by douglascrp** [comment]
@loftux One more property that should be included into alfresco-global.properties in order to ensure this is not going to happen again:
events.subsystem.autoStart=false
