### ISSUE TITLE
LibreOffice script is pointing to LibreOffice 6.1 instead of 6.2

### ISSUE THREAD

**Issue by douglascrp** [loftuxab/alfresco-ubuntu-install#121]
There is a small typo in the script.
https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/scripts/libreoffice.sh#L34

Version should be 6.2

**Comment by loftux** [comment]
This script is not really needed any more since both Alfresco versions (Alfresco official and ours) are using JodConverter now.

**Comment by douglascrp** [comment]
Indeed

**Comment by douglascrp** [comment]
Fixed by #136
