### ISSUE TITLE
The current onfiguration of max size for transformations does not apply for JodConverter

### ISSUE THREAD

**Issue by douglascrp** [loftuxab/alfresco-ubuntu-install#124]
In order to have JodConverter respecting/using the configured max size transformation sizes, it is required to use the following configuration into alfresco-global.properties

https://github.com/Alfresco/alfresco-repository/blob/master/src/main/resources/alfresco/subsystems/Transformers/default/transformers.properties#L185-L209

**Comment by loftux** [comment]
Now resolved, thanks for the fix
