### ISSUE TITLE
urls on artifacts.alfresco.com not detected during remote check

### ISSUE THREAD

**Issue by marsbard** [loftuxab/alfresco-ubuntu-install#37]
someone just came into IRC, I told them to run your script and he got these errors despite the URLs being available, looks like the "wget -spider" or whatever it was is failing for files from that domain

./alfinstall.sh 

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Alfresco Ubuntu installer by Loftux AB.
Please read the documentation at
https://github.com/loftuxab/alfresco-ubuntu-install.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Checking for the availability of the URLs inside script...
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

In alfinstall.sh, please fix this URL: https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/integrations/alfresco-googledocs-repo/2.0.8/alfresco-googledocs-repo-2.0.8.amp
In alfinstall.sh, please fix this URL: https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/integrations/alfresco-googledocs-share/2.0.8/alfresco-googledocs-share-2.0.8.amp
In alfinstall.sh, please fix this URL: https://artifacts.alfresco.com/nexus/service/local/repo_groups/public/content/org/alfresco/alfresco-spp/5.0.b/alfresco-spp-5.0.b.amp

Please fix the above errors and rerun.

**Comment by loftux** [comment]
Thinks this might have been resolved with the merge 2226002a1b7135e13b664274f57e4bbf706b5edd and no-strict check
