### ISSUE TITLE
Login authentication not working

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#46]
The script installs alfresco 5, and the login page for share comes up, but authentication isn't working.
Tried usernames configured during the database install script (alfresco and postgres), and a built in unix account (root).  None of them are able to login.
Any suggestions on getting authentication to work.

**Comment by BPCP** [comment]
The install has the default user admin with password admin

**Comment by chris001** [comment]
Trying to login with admin/admin is giving "Your authentication details have not been recognized or Alfresco may not be available at this time."

**Comment by loftux** [comment]
This is not an issue with the installer script and I cannot give support here. Post your alfresco log file (absolutely necessary to find the cause of your issue) to Alfresco forums or the irc http://chat.alfresco.com/.
If you still think this is an issue with the installer, please provide a way to reproduce and how the installer script has caused the issue.
