### ISSUE TITLE
Remove swftools from installer since html5 viewer is default

### ISSUE THREAD

**Issue by loftux** [loftuxab/alfresco-ubuntu-install#48]
It has been raised that the swf viewer is no longer used in 5.0, and thus the swftools part can be removed.

**Comment by loftux** [comment]
While the html5 viewer is default, the flash based one can still work as a fallback. Not all browser support the PdfJs html5 viewer. swftools is also usable for general transformation purposes. Leaving the swftools in for now.

**Comment by chris001** [comment]
If pdf2swf (swftools) were really required for viewing pdf in browser, then ipad viewing of pdf in apple safari browser (for ipad) would fail...?!

**Comment by loftux** [comment]
The Alfresco Viewer contains a fallback system, it will test each available viewer and format in order. Test will be evaluated by content format, browser, transformation options and more. So yes, it may fail, but then the last fallback is to render an image of the first page of the document.
