### ISSUE TITLE
libreoffice startup script.  incorrect temp folder.  fails to create it.

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#49]
# /opt/alfresco/scripts/libreoffice.sh start
    Alfresco Open Office starting
    # mkstemp("/home/alfresco/.execoooXOvs6U") failed: No such file or directory

**Comment by loftux** [comment]
This is a side effect of creating the alfresco as a system user without a home directory. It can be ignored, or you can manually create the directory
sudo mkdir -p /home/alfresco
sudo chown -R alfresco:alfresco /home/alfresco
