### ISSUE TITLE
admin and 2x databases username/password

### ISSUE THREAD

**Issue by chris001** [loftuxab/alfresco-ubuntu-install#53]
Where is it in this alfresco-ubunutu-install.sh that the initial admin login username/password is set?

Where on the system the username/password stored? In "postgres database? In "alfresco" database? Which tables?

The postgresql.sh script sets "postgres" username, and prompts for a password, for the database "postgres", and sets the "alfresco" username for the database "alfresco", without any password.

What purpose is to create the "alfresco" username, add it to database "alfresco", without any password, while the script displays instructions "Remember to update alfresco-global.properties with the alfresco database password"?

**Comment by loftux** [comment]
The script displays instructions on how to update the password: https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/scripts/postgresql.sh#L24
If you need further instructions on how to use postgres, have a look at their documentation.
