### ISSUE TITLE
Add Record Management to Install script 

### ISSUE THREAD

**Issue by gb-neptune** [loftuxab/alfresco-ubuntu-install#55]

**Comment by loftux** [comment]
Thanks for the suggestion.
However I would like to keep the install scripts as simple as possible, and most installs wont use RM. 
It is also not a one to one match, when new versions of Alfresco comes out, the current RM may or may not work with that version. So then I would have to remove the RM install support temporarily.

For those who do want to use it is very simple to download and apply the amps when needed. The install scripts add "helpers" for that https://github.com/loftuxab/alfresco-ubuntu-install#addons---manage-amps-and-war-files. Just add the amp files and apply them.

**Comment by gb-neptune** [comment]
understood
