### ISSUE TITLE
Limits setting not picked up when using upstart

### ISSUE THREAD

**Issue by loftux** [loftuxab/alfresco-ubuntu-install#56]
upstart jobs do not respect /etc/security/limits.conf
https://bugs.launchpad.net/ubuntu/+source/upstart/+bug/938669

Add in alfresco.conf:

limit nofile 8192 65536

**Comment by douglascrp** [comment]
I think this is the solution, right?
http://serverfault.com/questions/440878/changing-open-files-limit-in-mysql-5-5/441720#441720

Including these lines (or something like these) in alfresco.conf, but using the alfresco user
# NB: Upstart scripts do not respect
# /etc/security/limits.conf, so the open-file limits
# settings need to be applied here.
limit nofile 32000 32000
limit nproc 32000 32000

**Comment by loftux** [comment]
douglascrp Do you have any idea what values we should use? The values 8192 65536 is what I've used before, but those are not necessarily the best ones.

**Comment by douglascrp** [comment]
@loftux I've just remembered you asked me a question about this.
I don't have a "right" number, but I know I've been using the numbers you defined, and have had no problems with them. 
So I think it's ok to keep them.
