### ISSUE TITLE
What is the default admin password?

### ISSUE THREAD

**Issue by pstinghua** [loftuxab/alfresco-ubuntu-install#62]
What is the default admin password?

**Comment by lowk3y** [comment]
admin / admin ?

**Comment by loftux** [comment]
Yes, the installer doesn't change the default password, so it is user admin with password admin. If you still cannot login, your repository has not started properly. Then turn to Alfresco Forums or IRC and supply the logs there and someone can help you.

**Comment by mdemirell** [comment]
How can I remove Alfresco and components (java, postgresql, libreoffice etc.).
