### ISSUE TITLE
Unable to access Alfresco after install

### ISSUE THREAD

**Issue by lukeberry99** [loftuxab/alfresco-ubuntu-install#63]
After a fresh install of Alfresco on a new machine (Vultr VPS, 8GB RAM) I am unable to access alfresco on either port 80/share or /alfresco or port 8080/share or /alfresco.

The error in the log is as follows:
2015-06-23 07:08:53,360 ERROR [org.apache.solr.core.CoreContainer] [coreLoadExecutor-5-thread-1] null:org.apache.solr.common.SolrException: Unable to create core: collection1

Any thoughts?

**Comment by loftux** [comment]
Unfortunately this is not enough to diagnose the issue. Please use the Alfresco Forums or Irc http://chat.alfresco.com (I hang out there regularly) to post more details and people will be able to help you out. The issue tracker here is not the correct place for this.
You also have the option to contact Loftux for commercial support.

I will close this for now as I do not think it is an issue with the installer. If you find that it is, please feel free to re-open.
