### ISSUE TITLE
Error: Could not find or load main class org.apache.catalina.startup.Bootstrap

### ISSUE THREAD

**Issue by tonycosma** [loftuxab/alfresco-ubuntu-install#65]
For some reason tomcat 7.63 is not installing correctly.
The $subj error can be found in my /opt/alfresco/tomcat/logs/catalina.out
Anyone had this issue before ?

**Comment by tonycosma** [comment]
never mind, I was just stupid, I was downloading the tomcat source code instead of binaries. :)

**Comment by loftux** [comment]
No problem, glad you resolved it.

**Comment by ashokcs** [comment]
@tonycosma you are not alone.

**Comment by ielhag** [comment]
@tonycosma Thank god I found your answer, I was about to pull out my hair!

**Comment by vivekverma16** [comment]
I have the same problem 
Error: Could not find or load main class org.apache.catalina.startup.Bootstrap
when I am run, my maven project

**Comment by shekharkadam** [comment]
Hello Vivek , 
1>download binary 
 2>unzip it  
3>copy apache root folder 4>place this to your program files 
5> set JAVA_HOME to C:\Program Files\Java\jdk_Your_version_num 
6> Run  C:\Program Files\apache-tomcat-Your_version_num\bin\startup.bat .... 
hope your tomcat will start 
1>download binary -> https://tomcat.apache.org/
  1.1> choose version of your choice and click "download"
  1.2> On next page under heading "Binary Distributions"- download zip and proceed to next steps.
All the best.
