### ISSUE TITLE
problem with nginx config and ssl

### ISSUE THREAD

**Issue by hpz24** [loftuxab/alfresco-ubuntu-install#68]
hi, 
i tried your ubuntu-install script and everything works correct (Ubuntu 14.04LTS), very good work!

Now i tried the ssl-generate script and made the certificates. Then i modified the nginx.conf and when i go to my site with https i get the error: 400 Bad Request - The plain HTTP request was sent to HTTPS port. 
I googled a few times and things, but i didn´t get the server to run with https:
What did i wrong?
thanks in advance!

        # Default server config. Update servername.
        server {
                listen        80 default_server ;
                listen   [::]:80 default_server ipv6only=on;
                #listen        443 ssl;
                listen        443 ssl spdy;
                server_name myserver.eu;

                root /opt/alfresco/www;
                index index.html index.htm;

                # Redirecto root requests to Share
                rewrite ^/$     /share;

                ssl                 on;
                ssl_certificate       /etc/nginx/ssl/alfserver.crt;
                ssl_certificate_key   /etc/nginx/ssl/alfserver.key;

                ssl_session_timeout  15m;

                ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
                ssl_ciphers  HIGH:!aNULL:!MD5;
                ssl_prefer_server_ciphers   on;

                # spdy Support, use add_header if you do not use redirection from http to https
                add_header        Alternate-Protocol  443:npn-spdy/2;
                spdy_headers_comp 4;

**Comment by loftux** [comment]
Can you try to comment out the listen to port 80, first two lines after server{ ? 
Or remove the default_server from that part?

**Comment by hpz24** [comment]
i commented out both entries...

 server {
                #listen        80 default_server ;
                #listen   [::]:80 default_server ipv6only=on;
                listen        443 ssl;
                #listen        443 ssl spdy;
}

... but i get another error message, looks like the first, but with new text:

Bad Request

Your browser sent a request that this server could not understand.
Reason: You're speaking plain HTTP to an SSL-enabled server port.
Instead use the HTTPS scheme to access this URL, please.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by loftux** [comment]
Very old issue, closing this is the supplied nginx config has been updated and should work.
