### ISSUE TITLE
issues on xubuntu behind proxy

### ISSUE THREAD

**Issue by AlainT** [loftuxab/alfresco-ubuntu-install#72]
i had to substitute sudo curl by sudo -E curl and sudo -s by sudo -E -s to make the script working behind http proxy

**Comment by AlainT** [comment]
need also to launch oracle java installer from root and not by sudo

**Comment by AlainT** [comment]
ttf-mscorefonts-installer fail to install, perform
apt-get install --reinstall ttf-mscorefonts-installer from root prompt

**Comment by loftux** [comment]
Think this is a special case, and can be adjusted as per above for users that needs it.
