### ISSUE TITLE
White Page with i try to lunch it

### ISSUE THREAD

**Issue by ychoucha** [loftuxab/alfresco-ubuntu-install#74]
Hello,

well i m installing the script on a ubuntun 14.04 LTS x64

but after script install,

i have whyte page whe i try to acces on Alfresco :+1: 
http://192.168.1.50:8080

so how debug please ?

 i do this : 

 tail -f /opt/alfresco/tomcat/logs/catalina.2015-10-22.log

Oct 22, 2015 12:12:37 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /opt/alfresco/tomcat/webapps/share.war has finished in 14,936 ms
Oct 22, 2015 12:12:37 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Oct 22, 2015 12:12:37 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8443"]
Oct 22, 2015 12:12:37 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Oct 22, 2015 12:12:37 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 59574 ms

so someon know what is wrong please ?

**Comment by loftux** [comment]
Please use the Alfresco Forums or Irc http://chat.alfresco.com (I hang out there regularly) to post more details and people will be able to help you out. The issue tracker here is not the correct place for this.
You also have the option to contact Loftux for commercial support.

I will close this for now as I do not think it is an issue with the installer. If you find that it is, please feel free to re-open.

But I think it may work if you add /share to the end of the url. If you also installed nginx, make sure you have restarted nginx at least once.  Then you can use port 80 and it will also redirect to /share.
