### ISSUE TITLE
Solr doesn't seem to work

### ISSUE THREAD

**Issue by vialcollet** [loftuxab/alfresco-ubuntu-install#75]
Good morning
I have installed a new server and transfered data from a previous deployment.
Now, the searches don't work in Alfresco. I suspect this is due to Solr not working fine.
How can I check Solr is installed properly?

Oh maybe something that might help. I have changed the data directories to target another drive. I have updated locations in alfresco-global.properties:

```
dir.root=/data/alf_data
dir.contentstore=${dir.root}/contentstore
dir.contentstore.deleted=${dir.root}/contentstore.deleted
dir.cachedcontent=${dir.root}/cachedcontent
dir.auditcontentstore=${dir.root}/audit.contentstore
dir.keystore=${dir.root}/keystore
dir.indexes=${dir.root}/lucene-indexes
dir.indexes.backup=${dir.root}/backup-lucene-indexes
solr.backup.alfresco.remoteBackupLocation=${dir.root}/backupsolr
solr.backup.archive.remoteBackupLocation=${dir.root}/backupsolr
```

Do you have to change somthing for Solr?

Thanks in advance!

**Comment by ionics** [comment]
i do confirm this issue:

2015-11-08 17:34:00,040  ERROR [solr.tracker.AbstractTracker] [SolrTrackerScheduler_Worker-3] Tracking failed
 org.alfresco.error.AlfrescoRuntimeException: 10080119 GetModelsDiff return status is 404
	at org.alfresco.solr.client.SOLRAPIClient.getModelsDiff(SOLRAPIClient.java:1091)
	at org.alfresco.solr.tracker.ModelTracker.trackModelsImpl(ModelTracker.java:249)
	at org.alfresco.solr.tracker.ModelTracker.trackModels(ModelTracker.java:207)
	at org.alfresco.solr.tracker.ModelTracker.doTrack(ModelTracker.java:167)
	at org.alfresco.solr.tracker.AbstractTracker.track(AbstractTracker.java:153)
	at org.alfresco.solr.tracker.TrackerJob.execute(TrackerJob.java:47)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:563)

**Comment by loftux** [comment]
If you have move the alf_data and everything in that folder you will have to update tomcat/conf/server.xml and solr4/conf/<core>/solrcore.properties.

Easies it you just create a symbolik link between /opt/alfresco/alf_data and /data/alf_data and it should work.

For further help, please use the Alfresco Forums or Irc http://chat.alfresco.com (I hang out there regularly) to post more details and people will be able to help you out. The issue tracker here is not the correct place for this.
You also have the option to contact Loftux for commercial support.

I will close this for now as I do not think it is an issue with the installer. If you find that it is, please feel free to re-open.

**Comment by vialcollet** [comment]
Thank you very much for your help. While writing the issue I realized that the data directory migration might be the issue. I'll go for the symbolic link.
Thanks again.

**Comment by vialcollet** [comment]
For information, I just had to update the data directory in these two files to make Solr4 working properly:
/opt/alfresco/solr4/archive-SpacesStore/conf/solrcore.properties
/opt/alfresco/solr4/workspace-SpacesStore/conf/solrcore.properties
