### ISSUE TITLE
Uninstall Script

### ISSUE THREAD

**Issue by thecortex** [loftuxab/alfresco-ubuntu-install#80]
Hello,

I need to uninstall the scripts since my machine froze in the middle. Also I use apache on localhost, and it was overridden by nginx.

Is there a way to safe uninstall all changes?

Thanks in advance~

**Comment by loftux** [comment]
Hi,

You will have to look into the script and see each of the individual install steps what it does install and then remove that. Sorry, I can't help you more, but there is no way to know why your particular machine froze.
