### ISSUE TITLE
ImageMagick path doesn't exist in Trusty so how is it working?

### ISSUE THREAD

**Issue by housni** [loftuxab/alfresco-ubuntu-install#83]
I noticed this ImageMagick line: https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/alfinstall.sh#L443

I can see that it's attempting to create a symlink to ImageMagick but as you can see from the [Trusty filelist](http://packages.ubuntu.com/trusty/amd64/imagemagick/filelist), the path doesn't exist.

This also applies to some ImageMagick configs in [alfresco-global.properties](https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/tomcat/alfresco-global.properties#L90). None of these paths seem to exist in Trusty so I'm wondering if I'm missing something or if this is a bug?

**Comment by loftux** [comment]
This may have changed with later version of Trusty (14.04.5?) then, and updated packages for ImageMagick.

**Comment by housni** [comment]
I checked [Precise](http://packages.ubuntu.com/precise/amd64/imagemagick/filelist) which is the previous LTS Ubuntu to Trusty. I even checked [Trusty Updates](http://packages.ubuntu.com/trusty-backports/amd64/imagemagick/filelist) with no luck.

However, image conversions happen. My guess is that the `img.*` configs are redundant and Alfresco 5.x use the configs to find ImageMagick. Is that possible?

**Comment by loftux** [comment]
Fixed in d49a08418288a0bc508f08a8a9e57c71c24da401

**Comment by loftux** [comment]
Closing this issue since the fix has been pushed to master.
