### ISSUE TITLE
FYI: pdf2swf won't work in 16.04

### ISSUE THREAD

**Issue by housni** [loftuxab/alfresco-ubuntu-install#86]
I attempted installation (after many modifications to the script due to packages being switched around in 16.04) and this is the one error I couldn't fix (from Tomcat logs):

```
016-08-26 17:51:54,506 ERROR content.transform.RuntimeExecutableContentTransformerWorker localhost-startStop-1 Failed to start a runtime executable content transformer: 
Execution result: 
os: Linux
command: /usr/local/bin/pdf2swf -V
succeeded: false
exit code: 1
out: 
err: Cannot run program "/usr/local/bin/pdf2swf": error=2, No such file or directory
2016-08-26 17:51:54,623 INFO management.subsystems.ChildApplicationContextFactory localhost-startStop-1 Startup of 'thirdparty' subsystem, ID: thirdparty, default complete
```

Apparently, this is unfixable:
https://bugs.launchpad.net/ubuntu/+source/swftools/+bug/1086220

I thought this information will be helpful to anyone attempting this.

**Comment by chris001** [comment]
pdf.js is the preferred way to view pdf, requiring with only javascript in the browser, this works on dekstop, laptop, phone, tablet.
pdf2swf has been removed because of serious security issues. It also fails on most mobile devices, tablets due to dependency on flash, so why even use it. Best to switch over to pdf.js

**Comment by housni** [comment]
This is actually used by Alfresco for transformations. See: http://docs.alfresco.com/community/references/dev-extension-points-content-transformer.html

So, Alfresco has to change it.
I suppose a workaround is to find something that does the job that pdf2swf does, wrap it in a bash script (so that we can map the arguments passed in by Alfresco with the new tool) and make it available via PATH.

Ugly workaround but a necessary one, until Alfresco makes the change.

**Comment by chris001** [comment]
@housni I realize it's used for transformations in 5.1, but let me tell you something.  To convert pdf to adobe flash (swf) in 2016 is totally outdated, deprecated, insecure, no longer recommended, not to mention another huge downside, it's totally incompatible with mobile devices.  Alfresco needs to replace the dependency on that tool with something safe and much better, and the best choice around right now is pdf.js

**Comment by housni** [comment]
Oh I agree with you but I'm just that this is what Alfresco is doing. For the Alfresco Community Edition, if we are to use their default installation, this is not something we can change. Their devs have to change this.

**Comment by chris001** [comment]
@housni I read the link you provided to the 5.1 docs:  http://docs.alfresco.com/community/references/dev-extension-points-content-transformer.html 
It shows how to add a transformation via an amp code files.  Let's ask @jpotts 
Jeff, is it possible to add pdf.js as the default transformation for all transformers which previously used the outdated insecure pdf2swf to transform a pdf for preview on the browser.  Essentially to replace pdf2swf.

**Comment by jpotts** [comment]
There is already an add-on available in the community to use pdf.js, see https://addons.alfresco.com/addons/media-viewers. As for getting it to be the default and removing pdf2swf from the Alfresco distribution entirely, that's up to @esplinr, but I think everyone in the community would support it.

**Comment by housni** [comment]
If Alfresco wants their default installation to work in 16.04, they'll be compelled to use something other than pdf2swf. I hope they choose pdf.js.

**Comment by loftux** [comment]
I'm not sure I understand this issue. The installation of swftools (that pdf2swf ist part of)was removed in this commit https://github.com/loftuxab/alfresco-ubuntu-install/commit/5e25506d791f7dc7400274d301fceefb04bb5b4d since Support for swf transformations has been removed in Alfresco.

Also pdf.js based viewer is now part of Alfresco as standard, so why the discussion on bringing in pdf.js?

**Comment by chris001** [comment]
@loftux you're right, swftools is not listed as required software for 5.1
http://docs.alfresco.com/5.1/concepts/prereq-install.html

**Comment by housni** [comment]
Oh I totally missed that commit @loftux, I was looking at an older version of the script.
