### ISSUE TITLE
Installing tomcat and moves to wrong folder

### ISSUE THREAD

**Issue by lcrodriguez** [loftuxab/alfresco-ubuntu-install#87]
I had a problem where tomcat folder was incorrectly moved to /tomcat/tomcat-{version}/ and broke the script.

I had to manually copy it.

**Comment by loftux** [comment]
Can you be more specific on what version of Ubuntu? Any error output?

**Comment by lcrodriguez** [comment]
I’ll try to replicate on the weekend and let you know exactly.
I’m using Ubuntu 14.04 version.

**Comment by loftux** [comment]
Is this still an issue?

**Comment by loftux** [comment]
No feedback, closing.
