### ISSUE TITLE
How to use the limitconvert script?

### ISSUE THREAD

**Issue by Coaxial** [loftuxab/alfresco-ubuntu-install#88]
I understand what it does and what the rationale is, but how do I tell Alfresco to use it?

**Comment by douglascrp** [comment]
@Coaxial You do so by setting it inside the alfresco-global.properties
Check it out here https://github.com/loftuxab/alfresco-ubuntu-install/blob/master/tomcat/alfresco-global.properties#L86

**Comment by loftux** [comment]
This is not really an issue, explained by @douglascrp so closing this.
@Coaxial If you have questions, use irc http://chat.alfresco.com I'm often there
