### ISSUE TITLE
Update for SDK 3 Jar deployment

### ISSUE THREAD

**Issue by akafortes** [loftuxab/alfresco-ubuntu-install#96]
Are there any plans to add JAR deployment options?

**Comment by loftux** [comment]
Hi,

You can already do drop them in modules/platform and modules/share respectively as part of this pull request https://github.com/loftuxab/alfresco-ubuntu-install/pull/85.
Or is it something else you mean?

**Comment by akafortes** [comment]
No, that's what I was looking for.
Do I still use the apply.sh after that?

**Comment by loftux** [comment]
No that is only for applying amps (merging them) to the war fil.

**Comment by akafortes** [comment]
OK, do I need to do anything else after I put the JARs in the corresponding folders?

**Comment by loftux** [comment]
Sorry, I don't that.

**Comment by akafortes** [comment]
If I create a jar for the platform and I put it in the modules/platform folder, do I have to do something else for the changes to go live?

**Comment by loftux** [comment]
Please continue the discussion on Alfresco IRC of Community forum.
