### ISSUE TITLE
LibreOffice version replacement suggestion

### ISSUE THREAD

**Issue by douglascrp** [loftuxab/alfresco-ubuntu-install#98]
Hey @loftux 

I was facing serious problems with the preview generation when using LibreOffice 5.3.
Try to preview the file below and you will see the problem
https://drive.google.com/open?id=0B2d7BMp8tlURbHdZNGJicjNJdG8

I can say that the problem is solved now that I replaced LibreOffice with the version LibreOffice 5.1.3.1

I have raised an issue in the LibreOffice project, and provided the file for them to test, but so far, I got no response from them.

Some information about the PDF generation for both LibreOffice versions:
Original file, 1,5 MB

With LibreOffice 5.3
10 to 15 minutes to generate, final PDF size = 82,5 MB

With LibreOffice 5.1
3 minutes to generate, final PDF size = 16 MB

I hope you find this information useful and accept the idea.

If you are curious, I was also playing with JODConverter. The result of my tests is here https://gist.github.com/douglascrp/9de344222edacdb7d8b8aa52fc4b99d1
Maybe we could include this by default in the install

**Comment by loftux** [comment]
I can confirm this, tested 5.3.3.2 and 5.1.6.2 locally on my Mac, same size results. Will change to use 5.1.6.2 by default.

**Comment by douglascrp** [comment]
@loftux Nice.
Thank you.

**Comment by loftux** [comment]
Can you provide a link to the issue filed with LibreOffice so that we can track when this get fixed?

**Comment by loftux** [comment]
This is the issue https://bugs.documentfoundation.org/show_bug.cgi?id=104479

**Comment by douglascrp** [comment]
@loftux Sorry, but I completely forgot about you asking me to post the link.
Thank you for doing it.

**Comment by douglascrp** [comment]
Hey @loftux 
I am back just to let you know that I have been using the LibreOffice 6.0. for this customer, which was the one where I detected the problem.
I got the deb files from this PPA https://launchpad.net/~libreoffice/+archive/ubuntu/ppa

**Comment by loftux** [comment]
@douglascrp I just tested with 6.0.4 for mac released yesterday, and it still have the same problem. The "kung fu" pptx becomes 82MB, when converted with Keynote on Mac the pdf is less than 1MB.
So is the PPA you linked different builds?

**Comment by douglascrp** [comment]
@loftux Sorry, but I should have explained what I did waaay better.

The older version fixed the problem with the kung fu pptx, but after months of use, our users started to face constant freeze even when trying to convert simple docx files. LibreOffice couldn't keep running for more than 1 minute or so, and because of that, I was forced to test newer versions.
This new version works well for "normal" files, but I haven't tested it with the original document.

Conclusion, with the version 5.1.6.2, the conversion was simply not working anymore. I guess this is because the Ubuntu packages have been upgraded since the downgrade.

Again, sorry for not making it clear.

**Comment by douglascrp** [comment]
@loftux I am not sure if you receive the updates from the LibreOffice issues, but it seems they are making some advances on the fix for this issue.
I received some emails in the last days about a new 6.x version they are about to release.
I will try with this version as soon as it is done and will let you know how it goes.

**Comment by loftux** [comment]
@douglascrp I've tested now with both 6.0.5.1 and 6.1 beta 1 on my mac, and no improvements. Still slow and produces large files.

**Comment by loftux** [comment]
@douglascrp Did some more testing, it actually works ok for most files, just not the Kung fu file :)

**Comment by douglascrp** [comment]
@loftux What do you think about waiting for the final release and use it as the default installed version?
After that, we could close this issue.
I don't believe this single document will be a problem again.

**Comment by douglascrp** [comment]
@loftux Please, ignore all my latest messages about upgrading LibreOffice.
After some days, we had to downgrade it on our server, because for some really simple files, LibreOffice simply couln't start.
We are studying some alternatives. The most promissing one so far seems to be this one https://github.com/cetra3/onlyoffice-alfresco#transformation
